### ISSUE TITLE
web app + UI

### ISSUE THREAD

**Issue by badutka** [Image-binarizer/frontend#1]
- [x] users login and registration
- [x] displaying binarized images
- [x] uploading single image
- [x] uploading many images at once (to discuss)
- [x] app deployment on Heroku

**Comment by wojciech-jakub** [comment]
I suggest l

**Comment by wojciech-jakub** [comment]
P

**Comment by wojciech-jakub** [comment]
i suggest to use semantic ui
